# Generated by Django 4.0.6 on 2023-03-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='users.notification', verbose_name='Уведомления'),
        ),
    ]
